In [3]:
import pandas as pd

In [5]:
data = pd.read_csv("Maternal Health Risk Data Set.csv")

In [6]:
data

      Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0      25         130           80  15.0      98.0         86  high risk
1      35         140           90  13.0      98.0         70  high risk
2      29          90           70   8.0     100.0         80  high risk
3      30         140           85   7.0      98.0         70  high risk
4      35         120           60   6.1      98.0         76   low risk
...   ...         ...          ...   ...       ...        ...        ...
1009   22         120           60  15.0      98.0         80  high risk
1010   55         120           90  18.0      98.0         60  high risk
1011   35          85           60  19.0      98.0         86  high risk
1012   43         120           90  18.0      98.0         70  high risk
1013   32         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]

In [27]:
from sklearn import preprocessing

In [ ]:
import numpy as np

In [30]:
# copy the data 
df_min_max_scaled = data.copy() 
  
# apply normalization techniques by Column 1 
column = 'Age'
df_min_max_scaled[column] = (df_min_max_scaled[column] - df_min_max_scaled[column].min()) / (df_min_max_scaled[column].max() - df_min_max_scaled[column].min())     
  
# view normalized data 
display(df_min_max_scaled)

           Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0     0.250000         130           80  15.0      98.0         86  high risk
1     0.416667         140           90  13.0      98.0         70  high risk
2     0.316667          90           70   8.0     100.0         80  high risk
3     0.333333         140           85   7.0      98.0         70  high risk
4     0.416667         120           60   6.1      98.0         76   low risk
...        ...         ...          ...   ...       ...        ...        ...
1009  0.200000         120           60  15.0      98.0         80  high risk
1010  0.750000         120           90  18.0      98.0         60  high risk
1011  0.416667          85           60  19.0      98.0         86  high risk
1012  0.550000         120           90  18.0      98.0         70  high risk
1013  0.366667         120           65   6.0     101.0         76   mid risk

[1014 rows x 7 columns]